### PR TITLE
adding neoG Component library files.

### PR DESCRIPTION
**Pull request by santhoshpemmaka**
Please give your reviews and suggestions. Feedback is highly appreciated.  :)

### CODE REVIEW

**Review by srishtigautam21 — APPROVED** [review]
your code seems fine just check once why the images are not round in the preview

**Review by iRohitGaur — APPROVED** [review]
Good to merge 👍🏻

**Comment by santhoshpemmaka** [comment]
> your code seems fine just check once why the images are not round in the preview



> your code seems fine just check once why the images are not round in the preview

Hi Srishti, I've updated the changes in images width in the badges and avatar. :)
Thanks.

**Comment by santhoshpemmaka** [comment]
> Good to merge 👍🏻

Thanks :)

**Review by santhoshpemmaka — COMMENTED** [review]
Submit reviews

**Pull request closed without merging**
